export const GET_POST='GET_POST';
export const GET_NEW_POSTS='GET_NEW_POSTS';
export const GET_POPULAR_POSTS='GET_POPULAR_POSTS';
export const SEARCH_POSTS="SEARCH_POSTS" 
export const GET_USER_POSTS="GET_USER_POSTS"
export const GET_FAVORITE_POSTS="GET_FAVORITE_POSTS"
export const SET_PREVIEW="SET_PREVIEW"

export const CREATE_COMMENT="CREATE_COMMENT"

export const LOGIN="LOGIN"
export const LOGOUT="LOGOUT"

export const TOGGLE_FULLSCREEN="TOGGLE_FULLSCREEN"