export const GET_POST = 'GET_POST';

export const GET_POSTS='GET_POSTS';
export const GET_NEW_POSTS = 'GET_NEW_POSTS';
export const GET_POPULAR_POSTS = 'GET_POPULAR_POSTS';
export const SEARCH_POSTS = "SEARCH_POSTS"
export const GET_USER_POSTS = "GET_USER_POSTS"
export const GET_FAVORITE_POSTS = "GET_FAVORITE_POSTS"
export const SET_PREVIEW = "SET_PREVIEW"

export const LOAD_NEXT_PAGE="LOAD_NEXT_PAGE";
export const LOAD_PREV_PAGE="LOAD_PREV_PAGE";
export const NEXT_NEW_POSTS = "NEXT_NEW_POSTS";
export const PREV_NEW_POSTS = "PREV_NEW_POSTS"
export const NEXT_SEARCH_POSTS = "NEXT_SEARCH_POSTS"
export const PREV_SEARCH_POSTS = "PREV_SEARCH_POSTS"
export const NEXT_POPULAR_POSTS = "NEXT_POPULAR_POSTS"
export const PREV_POPULAR_POSTS = "PREV_POPULAR_POSTS"
export const NEXT_FAVORITE_POSTS = "NEXT_FAVORITE_POSTS"
export const PREV_FAVORITE_POSTS = "PREV_FAVORITE_POSTS"
export const NEXT_USER_POSTS = "NEXT_USER_POSTS"
export const PREV_USER_POSTS = "PREV_USER_POSTS"

export const CREATE_COMMENT = "CREATE_COMMENT"

export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

export const TOGGLE_FULLSCREEN = "TOGGLE_FULLSCREEN"